[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-railway-app-url.railway.app/api"

[context.branch-deploy.environment]
  VITE_API_URL = "https://your-railway-app-url.railway.app/api"